# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

# Needs BCGControlBar Pro plus VS MFC.
smt_mfc_shared_library("SmtGuiCore") {
  defines = [ "Export_SmtGuiCore" ]
  sources = [
    "Dlg2DFeatureInfo.cpp",
    "DlgAttStructSet.cpp",
    "DlgInputText.cpp",
    "DlgSelectOne.cpp",
    "EditConfigDockBar.cpp",
    "SmtGuiCore.rc",
    "SysConfigDockBar.cpp",
    "smt_gui_api.cpp",
    "stdafx.cpp",
  ]
  deps = [
    "//src/SmtCore:SmtCore",
    "//src/SmtMFCExCore:SmtMFCExCore",
    "//src/SmtSysCore:SmtSysCore",
  ]
}
