# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

# Needs BCGControlBar Pro (BCGCBProInc.h) plus VS MFC.
smt_mfc_shared_library("SmtMFCExCore") {
  defines = [ "Export_SmtMFCExCore" ]
  include_dirs = [ "gridctrl" ]
  sources = [
    "Container.cpp",
    "SmtMFCExCore.cpp",
    "SmtMFCExCore.rc",
    "StackedWndDockBar.cpp",
    "TabbedWndDockBar.cpp",
    "gridctrl/BtnDataBase.cpp",
    "gridctrl/GridBtnCell.cpp",
    "gridctrl/GridBtnCellBase.cpp",
    "gridctrl/GridBtnCellCombo.cpp",
    "gridctrl/GridCell.cpp",
    "gridctrl/GridCellBase.cpp",
    "gridctrl/GridCellCheck.cpp",
    "gridctrl/GridCellCombo.cpp",
    "gridctrl/GridCellDateTime.cpp",
    "gridctrl/GridCellNumeric.cpp",
    "gridctrl/GridCtrl.cpp",
    "gridctrl/GridDropTarget.cpp",
    "gridctrl/GridURLCell.cpp",
    "gridctrl/InPlaceEdit.cpp",
    "gridctrl/InPlaceList.cpp",
    "gridctrl/TitleTip.cpp",
    "stdafx.cpp",
  ]
  deps = [ "//src/SmtCore:SmtCore" ]
}
