# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_proj") {
  dll_stem = "plugin_proj"
  sources = [
    "dlg_map_prj.cpp",
    "dlg_map_prj_do_grid.cpp",
    "dlg_map_prj_do_xy.cpp",
    "map_project.cpp",
    "map_project.rc",
    "mapprj_plug.cpp",
    "stdafx.cpp",
  ]
  include_dirs += [ "//src" ]
  deps = [
    "//src/plugin/host:legacy_cmd",
    "//src/plugin/legacy:plugin",
    "//src/base:base",
    "//src/base:core",
    "//src/algorithm/proj:proj",
    "//src/legacy/ui/xcatalog:xcatalog",
    "//src/algorithm/geo:geo",
    "//src/gis/map:gis",
    "//src/sys:sys",
    "//src/legacy/tool:tool",
    "//third_party:gdal",
  ]
}
