# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")
import("//testing/test.gni")

copy("traffic_resources") {
  sources = [
    "resources/shortest_path.ui.css",
    "resources/shortest_path.ui.xml",
  ]
  outputs = [ "$root_out_dir/../plugins/traffic/{{source_file_part}}" ]
}

source_set("traffic_views") {
  sources = [
    "commands.cc",
    "commands.h",
    "views/shortest_path_dialog.cc",
    "views/shortest_path_dialog.h",
  ]
  include_dirs += [
    ".",
    "//src",
  ]
  deps = [
    "//src/content:content",
    "//src/gis:gis",
    "//src/plugin/runtime/host:host",
    "//src/plugin/runtime/widgets:widgets",
    "//src/ui/views:views",
    "//third_party:gdal",
    "//third_party:rapidjson",
  ]
  data_deps = [ ":traffic_resources" ]
}

test("traffic_path_test") {
  output_name = "traffic_path_test"
  sources = [ "tests/path_test.cc" ]
  include_dirs += [ "//src" ]
  deps = [
    ":traffic_views",
    "//src/content:content",
    "//src/gis:gis",
    "//src/plugin/runtime/host:host",
    "//third_party:gdal",
  ]
  data_deps = [
    ":traffic_resources",
    "//third_party:gdal_runtime_dlls",
  ]
}
