# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("sde_mem") {
  dll_stem = "sde_mem"
  defines = [ "SDE_MEM_EXPORTS" ]
  sources = [
    "memtitlelayer.cpp",
  ]
  deps = [
    "//src/base:base",
    "//src/base:core",
    "//src/algorithm/geo:geo",
    "//src/sdb/map:gis",
    "//third_party:CxImage",
  ]
}