# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("SmtAM3DModelCreater") {
  sources = [
    "3dmodlecreater_plugin.cpp",
    "SmtAM3DModelCreater.cpp",
    "SmtAM3DModelCreater.rc",
    "stdafx.cpp",
  ]
  deps = [
    "//src/SmtAuxModule:SmtAuxModule",
    "//src/SmtCore:SmtCore",
  ]
}
