# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtSDEWSDevice") {
  defines = [ "Export_SmtSDEWSDevice" ]
  sources = [
    "sde_wsdatasource.cpp",
    "sde_wstitlelayer.cpp",
  ]
  deps = [
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
    "//src/SmtGisCore:SmtGisCore",
    "//src/SmtNetCore:SmtNetCore",
    "//src/SmtSDEMemDevice:SmtSDEMemDevice",
    "//third_party/CxImage:CxImage",
  ]
}