# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("Smt3DMathLib") {
  defines = [ "Export_Smt3DMathLib" ]
  sources = [
    "ml3d_aabb.cpp",
    "ml3d_api.cpp",
    "ml3d_matrix.cpp",
    "ml3d_obb.cpp",
    "ml3d_plane.cpp",
    "ml3d_polygon.cpp",
    "ml3d_ray.cpp",
    "ml3d_vector2.cpp",
    "ml3d_vector3.cpp",
    "ml3d_vector4.cpp",
  ]
  deps = [ "//src/SmtCore:SmtCore" ]
}