# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtBaseLib") {
  defines = [ "Export_SmtBaseLib" ]
  sources = [
    "bl_api.cpp",
    "bl_envelope.cpp",
    "bl_style.cpp",
    "bl_stylemanager.cpp",
    "bl_styletable.cpp",
  ]
  deps = [ "//src/SmtCore:SmtCore" ]
}
