# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Stub for the in-process `smartgis` embed (and worker JSON-RPC names)."""

from typing import Any, Callable, Optional

class Host:
    def contribute_command(
        self,
        plugin_id: str,
        command_id: str,
        title: str,
        menu: str,
        handler: Callable[[str], bool],
    ) -> bool: ...
    def contribute_dialog(
        self, plugin_id: str, dialog_id: str, title: str, factory: Callable[[], Any]
    ) -> bool: ...
    def contribute_dock(
        self,
        plugin_id: str,
        dock_id: str,
        title: str,
        area: str,
        factory: Callable[[], Any],
    ) -> bool: ...
    def contribute_processing(
        self,
        plugin_id: str,
        processing_id: str,
        title: str,
        factory: Callable[[str], bool],
    ) -> bool: ...
    def contribute_menu(
        self, plugin_id: str, menu_id: str, title: str, parent: str = "tools"
    ) -> bool: ...
    def contribute_export_frame(
        self,
        plugin_id: str,
        frame_id: str,
        min_lon: float,
        min_lat: float,
        max_lon: float,
        max_lat: float,
    ) -> bool: ...
    def lookup_export_frame(
        self, frame_id: str
    ) -> Optional[tuple[float, float, float, float]]: ...
    def execute(
        self, command_id: str, payload: str = "", view_id: int = 0
    ) -> bool: ...
    def withdraw(self, plugin_id: str) -> bool: ...
    def list_contributions(self, kind: str = "command") -> list[dict[str, str]]: ...
    def open_dialog(self, dialog_id: str) -> bool: ...
    def open_dock(self, dock_id: str) -> bool: ...
    def open_report(self, path: str) -> bool: ...
    def post_to_report(self, json: str) -> bool: ...
    def close_report(self) -> bool: ...
    def present_dataset(
        self, plugin_id: str, path: str = "", face: int = 0, surface: int = -1
    ) -> bool: ...
    def set_present_surface(self, surface: int) -> bool: ...
    def present_surface(self) -> int: ...
    def run_processing(self, processing_id: str, args_json: str = "{}") -> bool: ...
    def has_capability(self, capability_id: str) -> bool: ...
    def playback_push(self, json: str) -> bool: ...
    def playback_count(self) -> int: ...
    def playback_set_index(self, i: int) -> bool: ...
    def playback_frame(self, i: int) -> Optional[str]: ...
    def playback_clear(self) -> bool: ...
    def scene3d_open_earth(self) -> bool: ...
    def scene3d_fly_to(
        self, lon: float, lat: float, distance: float = 1.2, span: float = 10.0
    ) -> bool: ...
    def scene3d_apply_look(self, mode_id: str) -> dict[str, Any]: ...
    def scene3d_set_atmosphere(
        self, sky: bool = True, ocean: bool = True, cloud: bool = False, fog: bool = False
    ) -> bool: ...
    def scene3d_invalidate(self) -> bool: ...
    def map2d_open_map(self) -> bool: ...
    def map2d_frame_to(self, lon: float, lat: float, span_deg: float) -> bool: ...
    def map2d_apply_look(self, mode_id: str) -> dict[str, Any]: ...
    def map2d_export_bmp(
        self, path: str, width: int = 1280, height: int = 720
    ) -> bool: ...
    def map2d_invalidate(self) -> bool: ...

class _Content:
    host: Host
    class events:
        @staticmethod
        def subscribe(name: str, fn: Callable[[], Any]) -> None: ...

class _Tool:
    @staticmethod
    def execute(id: str, view_id: int = 0, payload: str = "") -> bool: ...
    @staticmethod
    def activate(tool_id: str, view_id: int = 0) -> bool: ...

class _Ui:
    class config:
        @staticmethod
        def themes() -> list[dict[str, str]]: ...
        @staticmethod
        def theme_id() -> str: ...
        @staticmethod
        def set_theme(id: str) -> bool: ...

    @staticmethod
    def Label(text: str = "") -> Any: ...
    @staticmethod
    def Button(text: str = "") -> Any: ...
    @staticmethod
    def Textfield() -> Any: ...
    @staticmethod
    def Checkbox(text: str = "") -> Any: ...
    @staticmethod
    def Widget() -> Any: ...
    @staticmethod
    def pick_open_file(pattern: str = "*.*") -> dict[str, Any]: ...
    @staticmethod
    def pick_save_file(pattern: str = "*.*") -> dict[str, Any]: ...
    @staticmethod
    def show_message_box(kind: str, text: str) -> None: ...
    @staticmethod
    def show_inspect(panel: str) -> bool: ...

class _Debug:
    @staticmethod
    def set_tracing(on: bool) -> None: ...
    @staticmethod
    def tracing_enabled() -> bool: ...
    @staticmethod
    def trace_event(name: str, cat: str) -> Any: ...
    @staticmethod
    def profile(name: str, cat: str = "plugin") -> Any: ...
    @staticmethod
    def show_tab(name: str) -> bool: ...

class _Gis:
    class analysis:
        @staticmethod
        def ops() -> list[dict[str, str]]: ...
        @staticmethod
        def run(id: str, **params: Any) -> dict[str, Any]: ...
        @staticmethod
        def buffer(distance: float = 0.05) -> dict[str, Any]: ...

    class scene:
        @staticmethod
        def layers() -> Any: ...
        @staticmethod
        def open(path: str) -> bool: ...

    class style:
        @staticmethod
        def has_document() -> bool: ...
        @staticmethod
        def load(path: str) -> bool: ...

content: _Content
tool: _Tool
ui: _Ui
debug: _Debug
gis: _Gis
Host: type[Host]
