# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Edit-time stubs for embed smartgis.ui (Views + dialogs)."""

from typing import Any, Callable, Optional

class Label: ...
class Button: ...
class Textfield: ...
class Checkbox: ...
class Widget: ...

def pick_open_file(pattern: str = ...) -> dict[str, Any]: ...
def pick_save_file(pattern: str = ...) -> dict[str, Any]: ...
def show_message_box(kind: str, text: str) -> None: ...

class config:
    @staticmethod
    def themes() -> list[dict[str, str]]: ...
    @staticmethod
    def theme_id() -> str: ...
    @staticmethod
    def set_theme(id: str) -> bool: ...
