# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Shell ThemeService / system UI config."""

def themes() -> list[dict[str, str]]: ...
def theme_id() -> str: ...
def set_theme(id: str) -> bool: ...
