# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_model3d") {
  dll_stem = "plugin_model3d"
  am_plugin = true
  precompiled_header = "stdafx.h"
  precompiled_source = "shell/stdafx.cpp"
  sources = [
    "shell/model3d_creater_plugin.cpp",
    "shell/model_3d_creater.cpp",
    "shell/model_3d_creater.rc",
    "shell/stdafx.cpp",
  ]
  include_dirs += [
    ".",
    "shell",
    "//src",
  ]
  deps = [
    "//src/legacy/plugin/runtime:cmd",
    "//src/legacy/plugin:plugin",
    "//src/base:core",
    "//src/legacy/tool:tool",
    "//src/base/math:math",
    "//src/gis/kernel/geo:geo",
    "//src/gis/model/map:gis",
    "//src/legacy/sys:sys",
    "//src/legacy/ui/catalog:xcatalog",
    "//src/legacy/ui/shell:xview",
    "//src/legacy/render/scene3d:scene3d",
    "//src/legacy/render/rhi3d:rhi",
    "//src/legacy/plugin/product/dem:plugin_dem",
    "//src/plugin/product/world3d:world3d_processing",
    "//third_party:gdal",
  ]
}
