# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("Smt3DMdLib") {
  defines = [ "Export_Smt3DMdLib" ]
  sources = [
    "md3d_2dgeoobject.cpp",
    "md3d_3dgeoobject.cpp",
    "md3d_cube.cpp",
    "md3d_northarray.cpp",
    "md3d_sphere.cpp",
    "md3d_water.cpp",
  ]
  deps = [
    "//src/Smt3DGeoCore:Smt3DGeoCore",
    "//src/Smt3DMathLib:Smt3DMathLib",
    "//src/Smt3DRenderer:Smt3DRenderer",
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
    "//src/SmtTinMesh:SmtTinMesh",
  ]
}