# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtBAOrthGrid") {
  defines = [ "Export_SmtBAOrthGrid" ]
  sources = [
    "baog_api.cpp",
    "baog_baorthgrid.cpp",
    "baog_baorthgrid_calpq_sl.cpp",
    "baog_baorthgrid_calpq_ttm.cpp",
    "baog_baorthgrid_calpq_voj.cpp",
    "baog_baorthgrid_calpq_w.cpp",
    "baog_baorthgrid_create.cpp",
    "baog_baorthgrid_modify.cpp",
    "baog_region.cpp",
  ]
  deps = [
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
    "//src/SmtGisCore:SmtGisCore",
    "//src/SmtMathLib:SmtMathLib",
  ]
}