// Copyright (c) 2026 The Mogu Authors.
// All rights reserved.
#ifndef _SMT_CORE_H
#define _SMT_CORE_H

#include "base/core/export.h"
// Legacy aliases until all trees stop including SMT_EXPORT_*.
#define SMT_EXPORT_DLL BASE_EXPORT
#define SMT_EXPORT_CLASS BASE_EXPORT
#define SMT_EXPORT_API BASE_EXPORT
#define SMT_EXPORT_DATA BASE_EXPORT

#define SmartVersion 1.0

#include <assert.h>
#include <stdarg.h>
#include <stdio.h>
// windows.h pulls windef.h; including windef.h first skips SDK setup of
// _AMD64_ / _X86_ and trips winnt.h "No Target Architecture".
#include <windows.h>

#ifndef TRACE
#ifdef _DEBUG
inline void SmtTrace(const char* fmt, ...) {
  char buf[1024];
  va_list ap;
  va_start(ap, fmt);
  _vsnprintf_s(buf, _TRUNCATE, fmt, ap);
  va_end(ap);
  OutputDebugStringA(buf);
}
#define TRACE SmtTrace
#else
#define TRACE(...) ((void)0)
#endif
#endif
#include <math.h>

#include <fstream>
#include <limits>
#include <map>
#include <string>
#include <vector>

using namespace std;

#define SMT_SAFE_DELETE(p) \
  {                        \
    if (p != NULL) {       \
      delete (p);          \
      (p) = NULL;          \
    }                      \
  }
#define SMT_SAFE_DELETE_A(p) \
  {                          \
    if (p != NULL) {         \
      delete[] (p);          \
      (p) = NULL;            \
    }                        \
  }

#if defined(BUILD_AS_DLL) || defined(BUILD_AS_DLL)
#if defined(_DEBUG)
#pragma comment(linker, "/NODEFAULTLIB:libcd.lib")
#else
#pragma comment(linker, "/NODEFAULTLIB:libc.lib")
#endif
#endif

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#pragma warning(disable : 4786)

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#pragma warning(disable : 4503)

// disable: "conversion from 'double' to 'float', possible loss of data
#pragma warning(disable : 4244)

// disable: "truncation from 'double' to 'float'
#pragma warning(disable : 4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#pragma warning(disable : 4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#pragma warning(disable : 4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception
// specifications in the ANSI C++ draft.
#pragma warning(disable : 4290)

// disable: "no suitable definition provided for explicit template
// instantiation request" Occurs in VC7 for no justifiable reason on all
// #includes of Singleton
#pragma warning(disable : 4661)

// disable: deprecation warnings when using CRT calls in VC8
// These show up on all C runtime lib code in VC8, disable since they clutter
// the warnings with things we may not be able to do anything about (e.g.
// generated code from nvparse etc). I doubt very much that these calls
// will ever be actually removed from VC anyway, it would break too much code.
#pragma warning(disable : 4996)

// disable: "conditional expression constant"
#pragma warning(disable : 201)

#define SMT_OK S_OK
#define SMT_FALSE S_FALSE

enum SmtErr {
  SMT_ERR_NONE = 0,
  SMT_ERR_FAILURE,
  SMT_ERR_UNKOWN,
  SMT_ERR_NOT_ENOUGH_MEM,

  SMT_ERR_OPEN_INNER,
  SMT_ERR_ARCHIVE_INNER,
  SMT_ERR_CREATE_INNER,
  SMT_ERR_SAVE_INNER,
  SMT_ERR_MATH_INNER,

  SMT_ERR_FUNC_INNER,

  SMT_ERR_INVALID_HANDLE,
  SMT_ERR_INVALID_PARAM,
  SMT_ERR_INVALID_FILE,

  SMT_ERR_UNSUPPORTED,
  SMT_ERR_UNSUPPORTED_DEVICE,
  SMT_ERR_UNSUPPORTED_FMTS,
  SMT_ERR_UNSUPPORTED_GEOTYPE,

  SMT_ERR_DS_INNER,
  SMT_ERR_DB_OPER,
  SMT_ERR_SMF_OPER,

  SMT_WRN_ALREADYEXIST,
};

namespace base {
enum eMouseStatusType {
  typeNoStatus,
  typeDLButtonDown,
  typeLButtonDown,
  typeLButtonUp,
  typeMouseMove,
  typeDRButtonDown,
  typeRButtonDown,
  typeRButtonUp,
  typeMouseWeel
};

enum eOperType {
  typeNoOper,
  typeAppendFeature,
  typeModifyFeature,
  typeAnalysis,
  typeViewMap
};
}  // namespace base

#define MAX_NAME_LENGTH 50
#define MAX_FILE_PATH MAX_PATH

#define SmtUnsetMarker 0
#define SmtSetMarker 1

#if defined(WIN32) || defined(_WIN32)
// VS 2015+ has snprintf. Defining it as _snprintf turns std::snprintf
// into std::_snprintf, which C++23 MSVC does not provide.
#if defined(_MSC_VER) && _MSC_VER < 1900
#ifndef snprintf
#define snprintf _snprintf
#endif
#endif
#endif

const double SMT_C_INVALID_DBF_VALUE = 1E+10;
const unsigned int SMT_C_INVALID_UINT_VALUE = 999999;
const int SMT_C_INVALID_INT_VALUE = 99999999;
const unsigned long SMT_C_INVALID_ULONG_VALUE = 999999;
const long SMT_C_INVALID_LONG_VALUE = 99999999;
const float SMT_C_INVALID_FLOAT_VALUE = 1E+10;

inline constexpr double dEPSILON = 1E-5;
inline constexpr double dPI = 3.1415926;

inline bool is_equal(double a, double b, double eps) {
  return fabs(a - b) < eps;
}

#define SMT_EQUAL(a, b) (is_equal((a), (b), dEPSILON))

#define toString(x) #x
// MSVC /Zc:preprocessor rejects the non-standard #@ charizing operator.
#define makeChar(x) (#x)[0]

#define SMT_THREAD_SAFE

#endif  //_SMT_CORE_H