# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtMapService") {
  defines = [ "Export_SmtMapService" ]
  sources = [
    "msvr_dirtilecache.cpp",
    "msvr_mapservice.cpp",
    "msvr_smftilecache.cpp",
  ]
  deps = [
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
    "//src/SmtGisCore:SmtGisCore",
    "//src/SmtRender:SmtRender",
    "//src/SmtSysCore:SmtSysCore",
    "//src/SmtXCatalogCore:SmtXCatalogCore",
    "//third_party/CxImage:CxImage",
  ]
}
