# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Edit-time stubs for embed + worker shared smartgis.gis surface."""

from typing import Any, Optional

def ops() -> list[dict[str, str]]: ...
def run(id: str, distance: float = ...) -> dict[str, Any]: ...
def buffer(distance: float = ...) -> dict[str, Any]: ...
def clip(distance: float = ...) -> dict[str, Any]: ...
