# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""MapScene façade (2D map + shared 3D document)."""

from typing import Any, Optional

def layers() -> list[dict[str, Any]]: ...
def select_layer(id: str) -> bool: ...
def set_visible(id: str, on: bool) -> bool: ...
def extent() -> Optional[dict[str, float]]: ...
def open(path: str) -> bool: ...
def write(path: str) -> bool: ...
def feature_count() -> int: ...
def present_mode() -> str: ...
def set_present_mode(mode: str) -> bool: ...
