# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Cartographic StyleDocument on the active MapScene."""

from typing import Any, Optional

def has_document() -> bool: ...
def load(path: str) -> bool: ...
def clear() -> None: ...
def summary() -> Optional[dict[str, Any]]: ...
