<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>SmartGis.Host</RootNamespace>
    <AssemblyName>SmartGis.Host</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
</Project>
