# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("Smt3DGeoCore") {
  defines = [ "Export_Smt3DGeoCore" ]
  sources = [
    "geo_3dapi.cpp",
    "geo_3dcurve.cpp",
    "geo_3dgeometry.cpp",
    "geo_3dgeometrycollection.cpp",
    "geo_3dlinearring.cpp",
    "geo_3dlinestring.cpp",
    "geo_3dmultilinestring.cpp",
    "geo_3dmultipoint.cpp",
    "geo_3dpoint.cpp",
    "geo_3dsurface.cpp",
  ]
  deps = [
    "//src/Smt3DMathLib:Smt3DMathLib",
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
  ]
}