// Copyright (c) 2026 The Mogu Authors.
// All rights reserved.

#include "gis/vista/frame/frame.h"

namespace gis {
namespace vista {

std::string default_carto_style_json() {
  // Land / water / river / road casing+fill / admin stroke / labels.
  // Colors are the cartographic RGB values, stored only in this document.
  // Road casing is an earlier line layer on source-layer "road".
  return "{"
         "\"version\":8,"
         "\"name\":\"carto\","
         "\"layers\":["
         "{"
         "\"id\":\"background\","
         "\"type\":\"background\","
         "\"paint\":{\"background-color\":\"#aad3df\",\"background-opacity\":1}"
         "},"
         "{"
         "\"id\":\"land\","
         "\"type\":\"fill\","
         "\"source-layer\":\"land\","
         "\"paint\":{\"fill-color\":\"#f5f3e9\",\"fill-opacity\":1}"
         "},"
         "{"
         "\"id\":\"water\","
         "\"type\":\"fill\","
         "\"source-layer\":\"water\","
         "\"paint\":{\"fill-color\":\"#a3ccff\",\"fill-opacity\":1}"
         "},"
         "{"
         // DEM shade after land/water so cream land still receives tint when
         // the host binds china_dem (under vectors = before river/roads).
         "\"id\":\"hillshade\","
         "\"type\":\"hillshade\","
         "\"paint\":{"
         "\"hillshade-illumination-direction\":335,"
         "\"hillshade-exaggeration\":2.0,"
         // Warm umber shadow (not near-black) so multiply reads as soft
         // relief rather than a hard grey cast rim on cream land.
         "\"hillshade-shadow-color\":\"#2a2418\","
         "\"hillshade-highlight-color\":\"#fff8f0\","
         "\"hillshade-accent-color\":\"#1a1810\""
         "}"
         "},"
         "{"
         // Optional density overlay (source-layer \"heatmap\"); silent when
         // no matching points. Style Spec paint names; CPU circle splat v1.
         "\"id\":\"heatmap\","
         "\"type\":\"heatmap\","
         "\"source-layer\":\"heatmap\","
         "\"paint\":{"
         "\"heatmap-radius\":24,"
         "\"heatmap-weight\":1,"
         "\"heatmap-intensity\":1,"
         "\"heatmap-color\":\"#ff6400\","
         "\"heatmap-opacity\":0.65"
         "}"
         "},"
         "{"
         "\"id\":\"river\","
         "\"type\":\"line\","
         "\"source-layer\":\"river\","
         // Country-frame stroke: width 1 on cream land is nearly invisible;
         // match leftover GDI river weight (#64a0d0 @ ~2.5px).
         "\"paint\":{"
         "\"line-color\":\"#4a8ab8\","
         "\"line-width\":2.5,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"round\",\"line-join\":\"round\"}"
         "},"
         "{"
         "\"id\":\"admin\","
         "\"type\":\"line\","
         "\"source-layer\":\"admin\","
         "\"paint\":{"
         "\"line-color\":\"#c4beb0\","
         "\"line-width\":1,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"round\",\"line-join\":\"round\"}"
         "},"
         "{"
         "\"id\":\"road-casing\","
         "\"type\":\"line\","
         "\"source-layer\":\"road\","
         // Product zoom_from_scale = 8+log2(scale); china overview ≈ zoom 11.
         // Match MapLibre national band (minzoom 5) so dual-stroke casing is
         // visible on the china showcase frame (was 12 → road_casing_frac=0).
         "\"minzoom\":5,"
         "\"paint\":{"
         "\"line-color\":\"#8a7040\","
         "\"line-width\":3.5,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"round\",\"line-join\":\"round\"}"
         "},"
         "{"
         "\"id\":\"road\","
         "\"type\":\"line\","
         "\"source-layer\":\"road\","
         "\"minzoom\":5,"
         "\"paint\":{"
         "\"line-color\":\"#e0c06a\","
         "\"line-width\":1.6,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"round\",\"line-join\":\"round\"}"
         "},"
         "{"
         "\"id\":\"label\","
         "\"type\":\"symbol\","
         "\"source-layer\":\"label\","
         "\"layout\":{"
         "\"symbol-placement\":\"point\","
         "\"text-field\":\"{name}\","
         "\"text-size\":13,"
         "\"text-anchor\":\"center\""
         "},"
         "\"paint\":{"
         "\"text-color\":\"#141820\","
         "\"text-halo-color\":\"#ffffff\","
         "\"text-halo-width\":2"
         "}"
         "},"
         "{"
         "\"id\":\"river-label\","
         "\"type\":\"symbol\","
         "\"source-layer\":\"river\","
         "\"minzoom\":12,"
         "\"layout\":{"
         "\"symbol-placement\":\"line\","
         "\"text-field\":\"{name}\","
         "\"text-size\":11,"
         "\"text-anchor\":\"center\""
         "},"
         "\"paint\":{"
         "\"text-color\":\"#141820\","
         "\"text-halo-color\":\"#ffffff\","
         "\"text-halo-width\":2"
         "}"
         "},"
         "{"
         "\"id\":\"road-label\","
         "\"type\":\"symbol\","
         "\"source-layer\":\"road\","
         "\"minzoom\":14,"
         "\"layout\":{"
         "\"symbol-placement\":\"line\","
         "\"text-field\":\"{name}\","
         "\"text-size\":11,"
         "\"text-anchor\":\"center\""
         "},"
         "\"paint\":{"
         "\"text-color\":\"#141820\","
         "\"text-halo-color\":\"#ffffff\","
         "\"text-halo-width\":2"
         "}"
         "}"
         "]"
         "}";
}

}  // namespace vista
}  // namespace gis
