// Copyright (c) 2026 The Mogu Authors.
// All rights reserved.

#include "gis/vista/frame/frame.h"

namespace gis {
namespace vista {

std::string default_carto_style_json() {
  // Land / water / river / road casing+fill / admin stroke / labels.
  // Colors are the cartographic RGB values, stored only in this document.
  // Road casing is an earlier line layer on source-layer "road".
  return "{"
         "\"version\":8,"
         "\"name\":\"carto\","
         "\"layers\":["
         "{"
         "\"id\":\"background\","
         "\"type\":\"background\","
         "\"paint\":{\"background-color\":\"#aad3df\",\"background-opacity\":1}"
         "},"
         "{"
         "\"id\":\"land\","
         "\"type\":\"fill\","
         "\"source-layer\":\"land\","
         "\"paint\":{\"fill-color\":\"#f5f3e9\",\"fill-opacity\":1}"
         "},"
         "{"
         "\"id\":\"water\","
         "\"type\":\"fill\","
         "\"source-layer\":\"water\","
         "\"paint\":{\"fill-color\":\"#a3ccff\",\"fill-opacity\":1}"
         "},"
         "{"
         "\"id\":\"river\","
         "\"type\":\"line\","
         "\"source-layer\":\"river\","
         "\"paint\":{"
         "\"line-color\":\"#64a0d0\","
         "\"line-width\":2,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"butt\",\"line-join\":\"miter\"}"
         "},"
         "{"
         "\"id\":\"admin\","
         "\"type\":\"line\","
         "\"source-layer\":\"admin\","
         "\"paint\":{"
         "\"line-color\":\"#c4beb0\","
         "\"line-width\":1,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"butt\",\"line-join\":\"miter\"}"
         "},"
         "{"
         "\"id\":\"road-casing\","
         "\"type\":\"line\","
         "\"source-layer\":\"road\","
         "\"paint\":{"
         "\"line-color\":\"#9a9a9a\","
         "\"line-width\":5,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"butt\",\"line-join\":\"miter\"}"
         "},"
         "{"
         "\"id\":\"road\","
         "\"type\":\"line\","
         "\"source-layer\":\"road\","
         "\"paint\":{"
         "\"line-color\":\"#ffffff\","
         "\"line-width\":3,"
         "\"line-opacity\":1"
         "},"
         "\"layout\":{\"line-cap\":\"butt\",\"line-join\":\"miter\"}"
         "},"
         "{"
         "\"id\":\"label\","
         "\"type\":\"symbol\","
         "\"source-layer\":\"label\","
         "\"layout\":{"
         "\"symbol-placement\":\"point\","
         "\"text-field\":\"{name}\","
         "\"text-size\":14,"
         "\"text-anchor\":\"center\""
         "},"
         "\"paint\":{\"text-halo-color\":\"#ffffff\",\"text-halo-width\":3}"
         "},"
         "{"
         "\"id\":\"river-label\","
         "\"type\":\"symbol\","
         "\"source-layer\":\"river\","
         "\"layout\":{"
         "\"symbol-placement\":\"line\","
         "\"text-field\":\"{name}\","
         "\"text-size\":11,"
         "\"text-anchor\":\"center\""
         "},"
         "\"paint\":{\"text-halo-color\":\"#ffffff\",\"text-halo-width\":2}"
         "},"
         "{"
         "\"id\":\"road-label\","
         "\"type\":\"symbol\","
         "\"source-layer\":\"road\","
         "\"layout\":{"
         "\"symbol-placement\":\"line\","
         "\"text-field\":\"{name}\","
         "\"text-size\":12,"
         "\"text-anchor\":\"center\""
         "},"
         "\"paint\":{\"text-halo-color\":\"#ffffff\",\"text-halo-width\":2}"
         "}"
         "]"
         "}";
}

}  // namespace vista
}  // namespace gis
