# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_model3d") {
  dll_stem = "plugin_model3d"
  sources = [
    "model3d_creater_plugin.cpp",
    "model_3d_creater.cpp",
    "model_3d_creater.rc",
    "stdafx.cpp",
  ]
  include_dirs += [ "//src" ]
  deps = [
    "//src/plugin/host:legacy_cmd",
    "//src/plugin/legacy:plugin",
    "//src/base:core",
    "//src/legacy_tool:tool",
    "//src/render/math:math",
    "//src/algorithm/geo:geo",
    "//src/sdb/map:gis",
    "//src/sys:sys",
    "//src/ui/xcatalog:xcatalog",
    "//src/ui/xview:xview",
    "//src/legacy_render/model3d:model3d",
    "//src/legacy_render/terrain:terrain",
    "//src/legacy_render/pointcloud:pointcloud",
    "//src/legacy_render/scene3d:scene3d",
    "//src/legacy_render/render3d:render3d",
    "//src/plugin/legacy/dem:plugin_dem",
    "//third_party:gdal",
  ]
}
