# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

# Compiled into //src/base:base (dll_stem = base).

source_set("sys_sources") {
  configs += [ "//build:legacy" ]
  defines = [
    "_USRDLL",
    "SYS_EXPORTS=1",
  ]
  sources = [ "sysmanager.cpp" ]
}

group("sys") {
  public_deps = [ "//src/base:base" ]
}
