# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("SmtAMMapServiceMgr") {
  sources = [
    "Dlg2DXView.cpp",
    "DlgMapClient.cpp",
    "DlgMapServiceMgr.cpp",
    "DlgSvrCfgBase.cpp",
    "DlgSvrCfgTile.cpp",
    "SmtAMMapServiceMgr.cpp",
    "SmtAMMapServiceMgr.rc",
    "mapservicemgr_plugin.cpp",
    "msvr_mgr_api.cpp",
    "stdafx.cpp",
  ]
  deps = [
    "//src/SmtAuxModule:SmtAuxModule",
    "//src/SmtCore:SmtCore",
    "//src/SmtGuiCore:SmtGuiCore",
    "//src/SmtSDEDeviceMgr:SmtSDEDeviceMgr",
    "//src/SmtXCatalogCore:SmtXCatalogCore",
    "//src/SmtXViewCore:SmtXViewCore",
  ]
}
