# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")
import("//testing/test.gni")

source_set("browser_sources") {
  sources = [
    "fake_report_browser.cc",
    "fake_report_browser.h",
    "report_browser.cc",
    "report_browser.h",
    "webview2_report_browser.cc",
    "webview2_report_browser.h",
  ]
  include_dirs += [ "//src" ]
  defines = [ "PLUGIN_HOST_EXPORTS" ]
  deps = [ "//third_party/webview2:webview2" ]
  libs = [
    "ole32.lib",
    "oleaut32.lib",
  ]
}

group("browser") {
  public_deps = [ "//src/plugin/runtime/host:host" ]
}

test("plugin_report_browser_test") {
  output_name = "plugin_report_browser_test"
  sources = [ "report_browser_test.cc" ]
  include_dirs += [ "//src" ]
  deps = [ ":browser_sources" ]
}
