# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_print") {
  dll_stem = "plugin_print"
  sources = [
    "dlg_2d_xview.cpp",
    "map_print.cpp",
    "map_print.rc",
    "mapprint_plugin.cpp",
    "stdafx.cpp",
  ]
  include_dirs += [ "//src" ]
  deps = [
    "//src/plugin/host:legacy_cmd",
    "//src/plugin/legacy:plugin",
    "//src/base:core",
    "//src/legacy/tool:tool",
    "//src/legacy/ui/xview:xview",
    "//src/legacy/ui/xcatalog:xcatalog",
    "//src/algorithm/geo:geo",
    "//src/gis/map:gis",
    "//third_party:gdal",
  ]
}
