# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtMapServerDevice111") {
  defines = [ "Export_SmtMapServerDevice111" ]
  sources = [
    "msvr_mapserverdevice111.cpp",
    "msvr_mapserverdevice111_wfs.cpp",
    "msvr_mapserverdevice111_wms.cpp",
    "msvr_mapserverdevice111_wmts.cpp",
    "msvr_wmscapabilities111.cpp",
  ]
  deps = [
    "//src/SmtCore:SmtCore",
    "//src/SmtMapServer:SmtMapServer",
    "//src/SmtMapService:SmtMapService",
    "//src/SmtNetCore:SmtNetCore",
  ]
}
