# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtGeoCore") {
  defines = [ "Export_SmtGeoCore" ]
  sources = [
    "geo_api.cpp",
    "geo_arc.cpp",
    "geo_curve.cpp",
    "geo_fan.cpp",
    "geo_geometry.cpp",
    "geo_geometrycollection.cpp",
    "geo_grid.cpp",
    "geo_linearring.cpp",
    "geo_linestring.cpp",
    "geo_multilinestring.cpp",
    "geo_multipoint.cpp",
    "geo_multipolygon.cpp",
    "geo_point.cpp",
    "geo_polygon.cpp",
    "geo_spline.cpp",
    "geo_tin.cpp",
  ]
  deps = [
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtMathLib:SmtMathLib",
  ]
}
