/*
File:    smt_core.h

Desc:    SmartGis����ͷ�ļ�

Version: Version 1.0

Writter:  �´���

Date:    2010.11.17

Copyright (c) 2026 The Mogu Authors.
All rights reserved.
*/
#ifndef _SMT_CORE_H
#define _SMT_CORE_H

#if defined(CORE_EXPORTS)
#define CORE_EXPORT __declspec(dllexport)
#else
#define CORE_EXPORT __declspec(dllimport)
#endif

// Legacy aliases until all trees stop including SMT_EXPORT_*.
#define SMT_EXPORT_DLL CORE_EXPORT
#define SMT_EXPORT_CLASS CORE_EXPORT
#define SMT_EXPORT_API CORE_EXPORT
#define SMT_EXPORT_DATA CORE_EXPORT

#define SmartVersion		1.0

#include <windows.h>
#include <windef.h>
#include <assert.h>
#include <stdarg.h>
#include <stdio.h>

#ifndef TRACE
#ifdef _DEBUG
inline void SmtTrace(const char* fmt, ...)
{
	char buf[1024];
	va_list ap;
	va_start(ap, fmt);
	_vsnprintf_s(buf, _TRUNCATE, fmt, ap);
	va_end(ap);
	OutputDebugStringA(buf);
}
#define TRACE SmtTrace
#else
#define TRACE(...) ((void)0)
#endif
#endif
#include <string>
#include <vector>
#include <limits>
#include <math.h>
#include <fstream>
#include <map>

using namespace std;

#define SMT_SAFE_DELETE(p)   {if(p!=NULL){ delete (p);   (p)=NULL;}}
#define SMT_SAFE_DELETE_A(p) {if(p!=NULL){ delete [](p); (p)=NULL;}}

#if defined(BUILD_AS_DLL) ||  defined(BUILD_AS_DLL)
#if    defined( _DEBUG)
#          pragma comment(linker,"/NODEFAULTLIB:libcd.lib")//ignore default library 
#      else
#          pragma comment(linker,"/NODEFAULTLIB:libc.lib")//ignore default library 
#	   endif   
#   endif

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning (disable : 4786)

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning (disable : 4503)

// disable: "conversion from 'double' to 'float', possible loss of data
#   pragma warning (disable : 4244)

// disable: "truncation from 'double' to 'float'
#   pragma warning (disable : 4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#   pragma warning (disable : 4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#   pragma warning (disable : 4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception
// specifications in the ANSI C++ draft.
#   pragma warning( disable : 4290 )

// disable: "no suitable definition provided for explicit template
// instantiation request" Occurs in VC7 for no justifiable reason on all
// #includes of Singleton
#   pragma warning( disable: 4661)

// disable: deprecation warnings when using CRT calls in VC8
// These show up on all C runtime lib code in VC8, disable since they clutter
// the warnings with things we may not be able to do anything about (e.g.
// generated code from nvparse etc). I doubt very much that these calls
// will ever be actually removed from VC anyway, it would break too much code.
#	pragma warning( disable: 4996)

// disable: "conditional expression constant"
#   pragma warning (disable : 201)

// everything run ok
#define SMT_OK							S_OK

// general error message ref
#define SMT_FALSE						S_FALSE

//������
enum SmtErr
{
	SMT_ERR_NONE					=0,	//��ȷ
	SMT_ERR_FAILURE,					//ʧ��
	SMT_ERR_UNKOWN,						//δ֪����
	SMT_ERR_NOT_ENOUGH_MEM,				//�ڴ治��

	SMT_ERR_OPEN_INNER,					//�򿪴���
	SMT_ERR_ARCHIVE_INNER,				//��ȡ����
	SMT_ERR_CREATE_INNER,				//��������
	SMT_ERR_SAVE_INNER,					//�������
	SMT_ERR_MATH_INNER,					//��ѧ����

	SMT_ERR_FUNC_INNER,					//�����ڲ�����

	SMT_ERR_INVALID_HANDLE,				//��Ч���
	SMT_ERR_INVALID_PARAM,				//��Ч����
	SMT_ERR_INVALID_FILE,				//��Ч�ļ�

	SMT_ERR_UNSUPPORTED,				//��֧��
	SMT_ERR_UNSUPPORTED_DEVICE,			//��֧�ֵ�����
	SMT_ERR_UNSUPPORTED_FMTS,			//��֧�ָ�ʽ
	SMT_ERR_UNSUPPORTED_GEOTYPE,		//��ȷ��֧�ּ�������

	SMT_ERR_DS_INNER,					//����Դ�ڲ�����
	SMT_ERR_DB_OPER,					//db��������
	SMT_ERR_SMF_OPER,					//smf��������
				
	SMT_WRN_ALREADYEXIST,				//��������Ѵ���
};

namespace base
{
	enum eMouseStatusType
	{
		typeNoStatus,
		typeDLButtonDown,
		typeLButtonDown,
		typeLButtonUp,
		typeMouseMove,
		typeDRButtonDown,
		typeRButtonDown,
		typeRButtonUp,
		typeMouseWeel
	};

	enum eOperType
	{
		typeNoOper,
		typeAppendFeature,
		typeModifyFeature,
		typeAnalysis,
		typeViewMap
	};
}

#define MAX_NAME_LENGTH					50
#define MAX_FILE_PATH					MAX_PATH

#define SmtUnsetMarker					0
#define SmtSetMarker					1


#if defined(WIN32) || defined(_WIN32)
// VS 2015+ has snprintf. Defining it as _snprintf turns std::snprintf
// into std::_snprintf, which C++23 MSVC does not provide.
#  if defined(_MSC_VER) && _MSC_VER < 1900
#     ifndef snprintf
#        define snprintf _snprintf
#     endif
#  endif
#endif

const double							SMT_C_INVALID_DBF_VALUE = 1E+10;
const unsigned int						SMT_C_INVALID_UINT_VALUE = 999999;
const int								SMT_C_INVALID_INT_VALUE = 99999999;
const unsigned long						SMT_C_INVALID_ULONG_VALUE = 999999;
const long								SMT_C_INVALID_LONG_VALUE = 99999999;
const float								SMT_C_INVALID_FLOAT_VALUE = 1E+10;

#define SMT_EQUAL(a,b)					(fabs(a - b) < 1E-5)

#define toString(x)						#x
// MSVC /Zc:preprocessor rejects the non-standard #@ charizing operator.
#define makeChar(x)						(#x)[0]

//////////////////////////////////////////////////////////////////////////
//
#define	SMT_THREAD_SAFE										//�̰߳�ȫ

#endif //_SMT_CORE_H