# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")
import("//testing/test.gni")

source_set("print_composer") {
  sources = [
    "composer/print_composer.cc",
    "composer/print_composer.h",
  ]
  include_dirs += [ "//src" ]
  libs = [
    "gdi32.lib",
    "user32.lib",
  ]
}

source_set("print_views") {
  sources = [
    "commands.cc",
    "commands.h",
    "views/print_preview_dialog.cc",
    "views/print_preview_dialog.h",
  ]
  include_dirs += [ "//src" ]
  deps = [
    ":print_composer",
    "//src/content:content",
    "//src/plugin/runtime/host:host",
    "//src/plugin/runtime/widgets:widgets",
    "//src/ui/views:views",
  ]
}

test("print_composer_test") {
  output_name = "print_composer_test"
  sources = [ "composer/print_composer_test.cc" ]
  include_dirs += [ "//src" ]
  deps = [ ":print_composer" ]
  libs = [
    "gdi32.lib",
    "user32.lib",
  ]
}
