# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtAppCore") {
  defines = [ "Export_SmtAppCore" ]
  sources = [ "app_smtapp.cpp" ]
  deps = [
    "//src/SmtAuxModule:SmtAuxModule",
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtSDEDeviceMgr:SmtSDEDeviceMgr",
    "//src/SmtSysCore:SmtSysCore",
    "//src/SmtToolCore:SmtToolCore",
    "//src/SmtXCatalogCore:SmtXCatalogCore",
  ]
}
