# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtTinMesh") {
  defines = [ "Export_SmtTinMesh" ]
  sources = [
    "tin_api.cpp",
    "tin_delaunay_divide.cpp",
    "tin_delaunay_incremental.cpp",
  ]
  deps = [
    "//src/Smt3DGeoCore:Smt3DGeoCore",
    "//src/Smt3DMathLib:Smt3DMathLib",
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
  ]
}