# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

# Aux-module box chrome. Compiled into //src/ui:ui_legacy.
source_set("xambox_sources") {
  configs += [
    "//build:legacy",
    "//build:mfc",
  ]
  defines = [
    "_USRDLL",
    "_AFXDLL",
    "_AFX_NO_DAO_SUPPORT",
    "_AFXEXT",
    "XAMBOX_EXPORTS",
  ]
  precompiled_header = "stdafx.h"
  precompiled_source = "stdafx.cpp"
  include_dirs += [ "." ]
  sources = [
    "xambox_core.rc",
    "amb_amboxmgrdocbar.cpp",
    "amb_xambox.cpp",
    "stdafx.cpp",
  ]
  deps = [
    "//src/base:base",
    "//src/base:core",
    "//src/plugin:plugin",
    "//src/sys:sys",
  ]
}

group("xambox") {
  public_deps = [ "//src/ui:ui_legacy" ]
}
