# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("SmtXViewCore") {
  defines = [ "Export_SmtXViewCore" ]
  sources = [
    "SmtViewCore.cpp",
    "SmtXViewCore.rc",
    "stdafx.cpp",
    "vw_2deditxview.cpp",
    "vw_2dwsxview.cpp",
    "vw_2dxview.cpp",
    "vw_3dxview.cpp",
    "vw_xview.cpp",
  ]
  deps = [
    "//src/Smt3DBaseLib:Smt3DBaseLib",
    "//src/Smt3DRenderer:Smt3DRenderer",
    "//src/SmtCore:SmtCore",
    "//src/SmtGisCore:SmtGisCore",
    "//src/SmtGroupToolCore:SmtGroupToolCore",
    "//src/SmtRender:SmtRender",
  ]
}
