# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtSDEMemDevice") {
  defines = [ "Export_SmtSDEMemDevice" ]
  sources = [
    "sde_memdatasource.cpp",
    "sde_memraslayer.cpp",
    "sde_memtitlelayer.cpp",
    "sde_memveclayer.cpp",
  ]
  deps = [
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
    "//src/SmtGisCore:SmtGisCore",
    "//third_party/CxImage:CxImage",
  ]
}