# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Type stubs for AgentClient NDJSON framing."""

from typing import Any, Callable, Mapping, Optional
import socket

class AgentError(RuntimeError): ...

EventHandler = Callable[[dict[str, Any]], None]

class AgentClient:
    def __init__(self, sock: socket.socket) -> None: ...
    @classmethod
    def connect(cls, agent_url: str, timeout: float = ...) -> AgentClient: ...
    def close(self) -> None: ...
    def __enter__(self) -> AgentClient: ...
    def __exit__(self, *args: object) -> None: ...
    def set_event_handler(self, handler: Optional[EventHandler]) -> None: ...
    def send_raw(self, message: Mapping[str, Any]) -> None: ...
    def read_raw(self) -> dict[str, Any]: ...
    def drain_events(self) -> list[dict[str, Any]]: ...
    def poll_event(self, timeout: float = ...) -> Optional[dict[str, Any]]: ...
    def call(
        self,
        method: str,
        params: Optional[Mapping[str, Any]] = ...,
    ) -> dict[str, Any]: ...
    def reconnect(self, agent_url: str, timeout: float = ...) -> AgentClient: ...

def parse_agent_url(agent_url: str) -> tuple[str, int]: ...
def encode_request(
    req_id: int,
    method: str,
    params: Optional[Mapping[str, Any]] = ...,
) -> bytes: ...
def decode_line(raw: bytes | str) -> dict[str, Any]: ...
