# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtGroupToolCore") {
  defines = [ "Export_SmtGroupToolCore" ]
  sources = [
    "gt_3dviewctrltool.cpp",
    "gt_appendfeaturetool.cpp",
    "gt_base3dtool.cpp",
    "gt_basetool.cpp",
    "gt_flashtool.cpp",
    "gt_grouptoolfactory.cpp",
    "gt_iacommandreceiver.cpp",
    "gt_inputlinetool.cpp",
    "gt_inputpointtool.cpp",
    "gt_inputregiontool.cpp",
    "gt_selecttool.cpp",
    "gt_viewctrltool.cpp",
    "gt_wsviewctrltool.cpp",
  ]
  deps = [
    "//src/SmtBaseLib:SmtBaseLib",
    "//src/SmtCore:SmtCore",
    "//src/SmtGeoCore:SmtGeoCore",
    "//src/SmtGisCore:SmtGisCore",
    "//src/SmtRender:SmtRender",
    "//src/SmtSysCore:SmtSysCore",
    "//src/SmtToolCore:SmtToolCore",
  ]
}