# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_proj") {
  dll_stem = "plugin_proj"
  am_plugin = true
  precompiled_header = "stdafx.h"
  precompiled_source = "shell/stdafx.cpp"
  sources = [
    "shell/map_project.cpp",
    "shell/map_project.rc",
    "shell/mapprj_plug.cpp",
    "shell/stdafx.cpp",
    "views/dlg_map_prj.cpp",
    "views/dlg_map_prj_do_grid.cpp",
    "views/dlg_map_prj_do_xy.cpp",
  ]
  include_dirs += [
    ".",
    "shell",
    "//src",
  ]
  deps = [
    "//src/legacy/plugin/runtime:cmd",
    "//src/legacy/plugin:plugin",
    "//src/base:base",
    "//src/base:core",
    "//src/gis/kernel/proj:proj",
    "//src/legacy/ui/catalog:xcatalog",
    "//src/gis/kernel/geo:geo",
    "//src/gis/model/map:gis",
    "//src/legacy/sys:sys",
    "//src/legacy/tool:tool",
    "//third_party:gdal",
  ]
}
