# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtMapServer") {
  defines = [ "Export_SmtMapServer" ]
  sources = [
    "msvr_mapserver.cpp",
    "msvr_mapservercapabilities.cpp",
    "msvr_mapserverdevice.cpp",
  ]
  deps = [
    "//src/SmtCore:SmtCore",
    "//src/SmtMapService:SmtMapService",
    "//src/SmtNetCore:SmtNetCore",
    "//src/SmtXCatalogCore:SmtXCatalogCore",
  ]
}
