# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

"""Emit Interact DSL (.il) text from compacted op dicts."""

from __future__ import annotations

from typing import Any


def _fmt_points(points: list[tuple[int, int]]) -> str:
    return ", ".join(f"[{p[0]}, {p[1]}]" for p in points)


def emit_il(
    ops: list[dict[str, Any]],
    *,
    script_name: str = "recorded",
    title_comment: str = "",
) -> str:
    lines: list[str] = [
        "// Copyright (c) 2026 The Mogu Authors.",
        "// All rights reserved.",
    ]
    if title_comment:
        lines.append(f"// {title_comment}")
    else:
        lines.append("// Auto-generated by loop/record/il_recorder (hybrid OS+agent).")
    lines.append("")
    lines.append(f'script "{script_name}" {{')
    lines.append("  window(activate);")
    lines.append("  pump(ms=200);")

    # Group consecutive @os ops into one seq @os block; emit @inproc standalone.
    os_buf: list[str] = []

    def flush_os() -> None:
        nonlocal os_buf
        if not os_buf:
            return
        lines.append("  seq @os {")
        for stmt in os_buf:
            lines.append(f"    {stmt}")
        lines.append("  }")
        os_buf = []

    for op in ops:
        driver = op.get("driver")
        name = op.get("op")
        if name == "pump":
            stmt = f"pump(ms={int(op.get('ms', 100))});"
            if driver == "inproc":
                flush_os()
                lines.append(f"  {stmt}")
            else:
                os_buf.append(stmt)
            continue
        if driver == "inproc":
            flush_os()
            if name == "select_map_tab":
                lines.append(
                    f"  select_map_tab({int(op.get('index', 0))}) @inproc;"
                )
            elif name == "mark":
                tok = str(op.get("token", "")).replace('"', '\\"')
                lines.append(f'  mark("{tok}") @inproc;')
            elif name == "run_command":
                cid = str(op.get("id", "")).replace('"', '\\"')
                lines.append(f'  run_command("{cid}") @inproc;')
            elif name == "window":
                action = str(op.get("action", "activate"))
                lines.append(f"  window({action}) @inproc;")
            else:
                lines.append(f"  // skipped unknown inproc op: {name}")
            continue

        # OS verbs
        if name == "click":
            os_buf.append(
                f"click(shell, {int(op['x'])}, {int(op['y'])});"
            )
        elif name == "rclick":
            os_buf.append(
                f"rclick(shell, {int(op['x'])}, {int(op['y'])});"
            )
        elif name == "drag":
            os_buf.append(
                "drag("
                f"x0={int(op['x0'])}, y0={int(op['y0'])}, "
                f"x1={int(op['x1'])}, y1={int(op['y1'])});"
            )
        elif name == "path":
            pts = op.get("points") or []
            os_buf.append(f"path({_fmt_points(pts)});")
        elif name == "pan_burst":
            os_buf.append(
                "pan_burst("
                f"count={int(op['count'])}, "
                f"x={int(op['x'])}, y={int(op['y'])}, "
                f"dx={int(op['dx'])}, dy={int(op['dy'])}, "
                f"pump_ms={int(op['pump_ms'])});"
            )
        elif name == "wheel_burst":
            os_buf.append(
                "wheel_burst("
                f"count={int(op['count'])}, "
                f"x={int(op['x'])}, y={int(op['y'])}, "
                f"delta={int(op['delta'])}, "
                f"pump_ms={int(op['pump_ms'])});"
            )
        elif name == "wheel":
            os_buf.append(
                f"wheel(x={int(op['x'])}, y={int(op['y'])}, "
                f"delta={int(op['delta'])});"
            )
        elif name == "key":
            os_buf.append(f"key({op.get('name', 'ESCAPE')});")
        else:
            os_buf.append(f"// skipped {name}")

    flush_os()
    lines.append("}")
    lines.append("")
    return "\n".join(lines)
