# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_print") {
  dll_stem = "plugin_print"
  am_plugin = true
  precompiled_header = "stdafx.h"
  precompiled_source = "shell/stdafx.cpp"
  sources = [
    "shell/map_print.cpp",
    "shell/map_print.rc",
    "shell/mapprint_plugin.cpp",
    "shell/stdafx.cpp",
    "views/dlg_2d_xview.cpp",
  ]
  include_dirs += [
    ".",
    "shell",
    "//src",
  ]
  deps = [
    "//src/legacy/plugin/runtime:cmd",
    "//src/legacy/plugin:plugin",
    "//src/base:core",
    "//src/legacy/tool:tool",
    "//src/legacy/ui/shell:xview",
    "//src/legacy/ui/catalog:xcatalog",
    "//src/gis/kernel/geo:geo",
    "//src/gis/model/map:gis",
    "//third_party:gdal",
  ]
}
