# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtMapServerDeviceMgr") {
  defines = [ "Export_SmtMapServerDeviceMgr" ]
  sources = [ "msvr_mapserverdevicemgr.cpp" ]
  deps = [
    "//src/SmtCore:SmtCore",
    "//src/SmtMapServer:SmtMapServer",
    "//src/SmtMapServerDevice111:SmtMapServerDevice111",
  ]
}
