# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

source_set("proj_views") {
  sources = [
    "map_prj_dialog.cc",
    "map_prj_dialog.h",
    "map_prj_grid_page.cc",
    "map_prj_grid_page.h",
    "map_prj_xy_page.cc",
    "map_prj_xy_page.h",
    "proj_commands.cc",
    "proj_commands.h",
  ]
  include_dirs += [
    "//src",
    "//src/algorithm/proj",
    "//src/base/core",
    "//src/sdb/carto",
  ]
  defines += [ "PLUGIN_PROJ_VIEWS_USE_PROJ_API" ]
  deps = [
    "//src/algorithm/proj:proj",
    "//src/content:content",
    "//src/plugin/host:host",
    "//src/ui/views:views",
  ]
}
