# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

# Layer / map / scene catalogs. Compiled into //src/legacy/ui:ui_legacy.
source_set("xcatalog_sources") {
  configs += [
    "//build:legacy",
    "//build:mfc",
  ]
  defines = [
    "_USRDLL",
    "_AFXDLL",
    "_AFX_NO_DAO_SUPPORT",
    "_AFXEXT",
    "XCATALOG_EXPORTS",
  ]
  precompiled_header = "stdafx.h"
  precompiled_source = "stdafx.cpp"
  include_dirs += [ "." ]
  sources = [
    "dlg_create_ds.cpp",
    "dlg_create_layer.cpp",
    "dlg_create_map.cpp",
    "dlg_sel_fcls.cpp",
    "dlg_sel_ds.cpp",
    "dlg_sel_layer.cpp",
    "xcatalog_core.rc",
    "3dobjxcatalog.cpp",
    "catalog_api.cpp",
    "dsxcatalog.cpp",
    "mapdocxcatalog.cpp",
    "mapmgr.cpp",
    "scenemgr.cpp",
    "xcatalog.cpp",
    "stdafx.cpp",
  ]
  deps = [
    "//src/base:base",
    "//src/base:core",
    "//src/algorithm/geo:geo",
    "//src/gis/map:gis",
    "//src/legacy/render/model3d:model3d",
    "//src/plugin:plugin",
    "//src/legacy/render/render3d:render3d",
    "//src/gis/datasource/mgr:sde_mgr",
    "//third_party:gdal",
    "//src/legacy/render/scene3d:scene3d",
    "//src/sys:sys",
    "//src/legacy/render/terrain:terrain",
    "//src/legacy/tool:tool",
  ]
}

group("xcatalog") {
  public_deps = [ "//src/legacy/ui:ui_legacy" ]
}
