# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("SmtAdoCore") {
  defines = [ "Export_SmtAdoCore" ]
  sources = [
    "ado_adoconnection.cpp",
    "ado_adorecordset.cpp",
  ]
  deps = [ "//src/SmtCore:SmtCore" ]
  libs = [ "comsuppw.lib" ]
}