# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("Smt3DPointCloud") {
  defines = [ "Export_Smt3DPointCloud" ]
  sources = [ "md3d_pointcloud.cpp" ]
  deps = [
    "//src/Smt3DBaseLib:Smt3DBaseLib",
    "//src/Smt3DMathLib:Smt3DMathLib",
    "//src/Smt3DMdLib:Smt3DMdLib",
    "//src/Smt3DRenderer:Smt3DRenderer",
    "//src/SmtCore:SmtCore",
  ]
}