# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("SmtAMDemCreater") {
  sources = [
    "DlgAbout.cpp",
    "DlgGridLoader.cpp",
    "DlgTinLoader.cpp",
    "SmtAMDemCreater.cpp",
    "SmtAMDemCreater.rc",
    "demcreater_plug.cpp",
    "stdafx.cpp",
  ]
  deps = [
    "//src/SmtAuxModule:SmtAuxModule",
    "//src/SmtCore:SmtCore",
    "//src/SmtDemCore:SmtDemCore",
  ]
}
