# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")
import("//testing/test.gni")

# Compiled into //src/algorithm:algorithm (dll_stem = algorithm).
source_set("geo_sources") {
  sources = [
    "geo_ops.cc",
    "grid.cpp",
    "tin.cpp",
  ]
  configs += [ "//build:legacy" ]
  defines = [
    "_USRDLL",
    "GEO_EXPORTS",
  ]
  public_deps = [ "//third_party:gdal" ]
  deps = [
    "//src/base:base",
    "//src/base:core",
  ]
}

group("geo") {
  public_deps = [ "//src/algorithm:algorithm" ]
}

group("geo_all") {
  public_deps = [ ":geo" ]
}

test("geo_ogr_test") {
  output_name = "geo_ogr_test"
  sources = [ "geo_ogr_test.cc" ]
  include_dirs += [
    "//src/algorithm/geo",
    "//src",
  ]
  deps = [
    ":geo",
    "//src/render/math:math",
    "//third_party:gdal",
  ]
  data_deps = [ "//third_party:gdal_runtime_dlls" ]
}
