# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_shared_library("app_core") {
  dll_stem = "app_core"
  defines = [ "APP_CORE_EXPORTS" ]
  sources = [ "app_smtapp.cpp" ]
  deps = [
    "//src/base:base",
    "//src/base:core",
    "//src/algorithm/geo:geo",
    "//src/sdb/map:gis",
    "//src/plugin:plugin",
    "//src/sdb/datasource/mgr:sde_mgr",
    "//src/sys:sys",
    "//src/legacy_tool:tool",
    "//src/legacy_ui/xcatalog:xcatalog",
  ]
}
