# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")

smt_mfc_shared_library("plugin_dem") {
  dll_stem = "plugin_dem"
  am_plugin = true
  defines = [ "PLUGIN_DEM_EXPORTS" ]
  precompiled_header = "stdafx.h"
  precompiled_source = "shell/stdafx.cpp"
  sources = [
    "shell/dem_creater.cpp",
    "shell/dem_creater.rc",
    "shell/demcreater_plug.cpp",
    "shell/stdafx.cpp",
    "views/dlg_about.cpp",
    "views/dlg_grid_loader.cpp",
    "views/dlg_tin_loader.cpp",
  ]
  include_dirs += [
    ".",
    "shell",
    "//src",
  ]
  deps = [
    "//src/plugin/product/dem:dem_processing",
    "//src/legacy/plugin/runtime:cmd",
    "//src/legacy/plugin:plugin",
    "//src/base:core",
    "//src/gis/kernel/geo:geo",
    "//src/gis/kernel/tin:tin",
    "//src/legacy/tool:tool",
    "//src/legacy/render/rhi3d:rhi",
    "//src/legacy/render/scene3d:scene3d",
    "//src/legacy/ui/shell:xview",
    "//src/legacy/ui/catalog:xcatalog",
    "//src/legacy/ui/widgets:mfc_ex",
    "//src/gis/model/map:gis",
    "//src/legacy/sys:sys",
    "//third_party:gdal",
  ]
}
