# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//build/smartgis.gni")
import("//testing/test.gni")

copy("geochem_resources") {
  sources = [
    "resources/analyze.ui.css",
    "resources/analyze.ui.xml",
  ]
  outputs = [ "$root_out_dir/../plugins/geochem/{{source_file_part}}" ]
}

source_set("geochem_views") {
  sources = [
    "commands.cc",
    "commands.h",
    "views/analyze_dialog.cc",
    "views/analyze_dialog.h",
  ]
  include_dirs += [
    ".",
    "//src",
  ]
  deps = [
    "//src/content:content",
    "//src/gis:gis",
    "//src/plugin/runtime/host:host",
    "//src/plugin/runtime/widgets:widgets",
    "//src/ui/views:views",
    "//third_party:gdal",
    "//third_party:rapidjson",
  ]
  data_deps = [ ":geochem_resources" ]
}

test("geochem_analyze_test") {
  output_name = "geochem_analyze_test"
  sources = [ "tests/analyze_test.cc" ]
  include_dirs += [ "//src" ]
  deps = [
    "//src/gis:gis",
    "//third_party:gdal",
  ]
  data_deps = [ "//third_party:gdal_runtime_dlls" ]
}
